### ISSUE TITLE
Run the program on Mac OS

### ISSUE THREAD

**Issue by phtu-cs** [1iyiwei/text2speech#3]
Is it possible to run this program on Mac OS?😊

**Comment by 1iyiwei** [comment]
@qisun0 has added a Google variation that might run on other platforms.

**Comment by qisun0** [comment]
This is my fork for Google Cloud TTS: https://github.com/qisun0/text2speech

**Comment by phtu-cs** [comment]
@qisun0 @1iyiwei  Thank you! I will take a look.
